# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
import pkg_resources
sys.path.insert(0, os.path.abspath('../..'))


# -- Project information -----------------------------------------------------

project = 'N.E.S.T.'
copyright = "2021, Gruppo 2"
author = 'Gruppo 2'
release = '0.1.0'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx.ext.autosectionlabel",
    "sphinx_js"
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'it'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# Print warnings on the page
keep_warnings = True

# Display more warnings than usual
nitpicky = True


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'sphinx_rtd_theme'

html_theme_options = {
    "style_nav_header_background": "#3B7097"
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Intersphinx options -----------------------------------------------------

intersphinx_mapping = {
    "python": ("https://docs.python.org/3.8", None),
    "sqlalchemy": ("https://docs.sqlalchemy.org/en/14/", None),
    "flask": ("https://flask.palletsprojects.com/en/1.1.x/", None),
    "flask_sqlalchemy": ("https://flask-sqlalchemy.palletsprojects.com/en/2.x/", None),
    "flask_jwt_extended": ("https://flask-jwt-extended.readthedocs.io/en/stable/", None),
    "flask_cors": ("https://flask-cors.readthedocs.io/en/latest/", None),
    "requests": ("https://docs.python-requests.org/en/master/", None),
    "apispec": ("https://apispec.readthedocs.io/en/latest/", None),
    "marshmallow": ("https://marshmallow.readthedocs.io/en/stable/", None),
    "tweepy": ("https://docs.tweepy.org/en/latest/", None),
    "nltk": ("https://www.nltk.org/", None),
}


# -- Setup function ----------------------------------------------------------

def setup(app):
    app.add_css_file('custom.css')


# -- Extension configuration -------------------------------------------------

todo_include_todos = True
todo_emit_warnings = True
smartquotes = False
js_source_path = "../../nest_frontend"
jsdoc_config_path = "../../conf.json"

# -- Automodule settings -----------------------------------------------------

autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'show-inheritance': False,
}
