/**
 * All strings contained in the app should be present in this dict.
 *
 * If a key is missing in a language, the italian one is displayed instead.
 *
 * Define format strings as in C#:
 * ```js
 * "Raggio di {number} km"
 * "{number} km radius"
 * ```
 */
export default {
    // 🇮🇹
    it: {
        appName: "N.E.S.T.",
        appFullName: "Noi Estraiamo Statistiche Tweet",
        welcomeToNest: "Benvenuto a N.E.S.T.!",

        resolutionTooSmall: "Per visualizzare correttamente questa applicazione è richiesto uno schermo con risoluzione 1366x768 o superiore.",
        ignore: "Visualizza comunque",

        server: "Scegli un server",
        baseURL: "Base URL",
        notLoggedIn: "Accesso non effettuato",
        login: "Accedi",
        email: "Email",
        passwd: "Password",

        dashboardTitle: "Crea una nuova repository",
        dashboard: "Dashboard",
        searchBy: "Ricerca per",
        byZone: "area",
        byHashtag: "hashtag",
        byUser: "utente",
        byRetweet: "retweet",
        isNotRetweetExplaination: "Nascondi i retweet.",
        byHasImage: "immagine",
        hasImageExplaination: "Mostra solo i tweet con immagine.",
        byTimePeriod: "arco di tempo",
        byContents: "contenuti",
        byHasPlace: "punto di interesse",
        hasPlaceExplaination: "Mostra solo i tweet a cui è associato un PoI.",
        timeBefore: "Prima",
        timeAfter: "Dopo",
        conditions: "Condizioni",
        createRepo: "Crea repository",
        repoName: "Nome repository",
        request: "Richiedi",
        filterOR: "Almeno una cond.",
        filterAND: "Tutte le cond.",
        rollback: "Annulla modifiche",
        save: "Salva modifiche",
        wordcloud: "Wordcloud",

        repositories: "Repositories",
        repoMenu: "Menu repository",
        repoEdit: "Modifica repository",
        menuActive: "Le tue repository attive",
        menuArchived: "Le tue repository archiviate",
        emptyMenu: "Non c'è nulla qui.",
        delete: "Elimina",
        share: "Condividi",
        unshare: "Rimuovi",
        archive: "Archivia",
        edit: "Modifica",
        created: "Creata",
        archived: "Archiviata",

        // TODO: migliorare, maybe?
        repoShare: "Condivisioni",
        availableUsers: "Utenti disponibili",
        sharingWith: "In condivisione con",

        alerts: "Allarmi",
        alertTitle: "I tuoi allarmi associati a questa repository",
        alertCreate: "Crea un allarme",
        alertName: "Nome allarme",
        createAlert: "Crea allarme",
        alertLimit: "Limite", //TODO: Migliorare?
        alertWindow: "Finestra (in ore)",

        notImplemented: "🚧 Non implementato.",

        settings: "Impostazioni",
        loggedInTitle: "Accesso effettuato",
        loggedInOn: "Al momento hai effettuato l'accesso su",
        loggedInAs: "come",
        logout: "Esci",
        switchTheme: "Cambia tema",
        darkMode: "Scuro",
        lightMode: "Chiaro",
        changeLang: "Cambia lingua",
        alertSettings: "Impostazioni allarmi",
        changeEmail: "Cambia il tuo indirizzo email",
        changePasswd: "Cambia la tua password",

        users: "Utenti",
        manageUsers: "Gestisci utenti",
        userList: "Elenco utenti",
        userCreate: "Crea nuovo utente",
        userName: "Username",
        create: "Crea",
        type: "Tipo",
        admin: "Amministratore",
        user: "Utente",

        repoDeleted: "Questa repository è stata eliminata.",
        hourlyGraph: "Grafico orario",
        visualMap: "Mappa",
        tweets: "Tweet",
        stats: "Statistiche",
        totTweets: "Tweet totali",
        dispTweets: "Tweet mostrati",
        dispTweetsPerc: "% di tweet mostrati",
        locTweets: "Tweet con posizione",
        locTweetsPerc: "% di tweet con posizione",
        contTweets: "Tweet con contenuto",
        contTweetsPerc: "% di tweet con contenuto",
        wordCount: "Totale parole",
        wordPop: "Parola più utilizzata",
        imgTweets: "Tweet con immagine",
        imgTweetsPerc: "% di tweet con immagine",
        postUniq: "Totale utenti che hanno postato",
        postPop: "Utente più attivo",
        filters: "Filtri",

        errorUserNotFound: "Errore: Utente non trovato.",
        errorUserWrongCredentials: "Errore: Username o password non validi.",
        errorUserNotAuthorized: "Errore: Non hai i permessi necessari per accedere a questa risorsa.",
        errorUserNotAdmin: "Errore: Non sei amministratore.",
        errorUserPreventSeppuku: "Errore: Non puoi eliminare te stesso dalla lista degli utenti!",
        errorDeletionError: "Errore: Qualcosa sta impedendo l'eliminazione dell'utente.", // ask balu?
        errorNotFound: "Errore: Risorsa non trovata.",
        errorMissingFields: "Errore: Uno o più campi richiesti non sono stati compilati.",
        errorAlreadyExists: "Errore: La risorsa esiste già.",
        errorEnumInvalid: "Errore: Tipo di dato sconosciuto.",
        errorUnknownError: "Errore sconosciuto.",
        errorNoJson: "Errore: È stata inviata una richiesta senza corpo.",
        errorRepositoryNotFound: "Errore: Repository non trovato.",
        errorRepositoryNotOwner: "Errore: Non sei il proprietario del repository!",
        errorRepositoryDepencencyFailure: "Errore: Qualcosa sta impedendo l'eliminazione del repository.",
        errorConditionNotFound: "Errore: Specificata una condizione non valida.",
        errorAlertNotFound: "Errore: Allarme non trovato.",
        errorAlertNoName: "Errore: Nome allarme non specificato.",
        errorAlertNoLimit: "Errore: Limite allarme non specificato.",
        errorAlertNoWindow: "Errore: Finestra di allarme non specificata.",
        errorAlertNoEvaluation: "Errore: Modalità di valutazione non specificata.",
        errorAlertDeletionFailure: "Errore: Qualcosa sta impedendo l'eliminazione dell'allarme.",
        errorViewNotAllowed: "Errore: Non è permesso effettuare la richiesta.",
        errorServerNotConfigured: "Errore: Non è stato configurato nessun server.",
        errorDecodeError: "Errore: Non è stato possibile deserializzare i dati ricevuti dal backend.",
        errorSerializationError: "Errore: Non è stato possibile serializzare i dati da inviare al backend.",
        errorPageNotFound: "Errore: Pagina non trovata.",
    },
    // 🇬🇧
    en: {
        appName: "N.E.S.T.",
        appFullName: "We Extract Statistics from Tweets",
        welcomeToNest: "Welcome to N.E.S.T.!",

        resolutionTooSmall: "To correctly visualize this application, a screen with resolution 1366x768 or higher is required.",
        ignore: "View anyway",

        server: "Choose a server",
        baseURL: "Base URL",
        notLoggedIn: "Not logged in",
        login: "Login",
        email: "Email",
        passwd: "Password",

        dashboardTitle: "Create a new repository",
        dashboard: "Dashboard",
        searchBy: "Search by",
        byZone: "zone",
        byHashtag: "hashtag",
        byUser: "user",
        byRetweet: "retweet",
        isNotRetweetExplaination: "Hide retweets.",
        byHasImage: "image",
        hasImageExplaination: "Only show tweets with an image.",
        byTimePeriod: "time period",
        byContents: "contents",
        byHasPlace: "point of interest",
        hasPlaceExplaination: "Only show tweets with an associated PoI.",
        timeBefore: "Before",
        timeAfter: "After",
        conditions: "Conditions",
        createRepo: "Create repository",
        repoName: "Repository name",
        request: "Request",
        filterOR: "At least one cond.",
        filterAND: "Every cond.",
        rollback: "Rollback changes",
        save: "Save changes",
        wordcloud: "Wordcloud",

        repositories: "Repositories",
        repoMenu: "Repositories menu",
        repoEdit: "Edit repository",
        menuActive: "Your active repositories",
        menuArchived: "Your archived repositories",
        emptyMenu: "There's nothing here.",
        delete: "Delete",
        share: "Share",
        unshare: "Unshare",
        archive: "Archive",
        edit: "Edit",
        created: "Created",
        archived: "Archived",

        repoShare: "Share",
        availableUsers: "Available users",
        sharingWith: "Sharing with",

        alerts: "Alerts",
        alertTitle: "Your alerts associated with this repository",
        alertCreate: "Create a new alert",
        alertName: "Alert name",
        createAlert: "Create alert",
        alertLimit: "Threshold",
        alertWindow: "Window size (in hours)",

        notImplemented: "🚧 Not implemented.",

        settings: "Settings",
        loggedInTitle: "Logged in",
        loggedInOn: "You are currently logged in at",
        loggedInAs: "as",
        logout: "Logout",
        switchTheme: "Switch theme",
        darkMode: "Dark",
        lightMode: "Light",
        changeLang: "Change language",
        alertSettings: "Alert settings",
        changeEmail: "Change your email address",
        changePasswd: "Change your password",

        users: "Users",
        manageUsers: "Manage users",
        userList: "User list",
        userCreate: "Create new user",
        userName: "Username",
        create: "Create",
        type: "Type",
        admin: "Admin",
        user: "User",

        repoDeleted: "This repository was deleted.",
        hourlyGraph: "Hourly graph",
        visualMap: "Map",
        tweets: "Tweets",
        stats: "Stats",
        totTweets: "Total tweets",
        dispTweets: "Displayed tweets",
        dispTweetsPerc: "% of displayed tweets",
        locTweets: "Tweets with location",
        locTweetsPerc: "% of tweets with location",
        contTweets: "Tweets with content",
        contTweetsPerc: "% of tweets with content",
        wordCount: "Word count",
        wordPop: "Most popular word",
        imgTweets: "Tweets with image",
        imgTweetsPerc: "% of tweets with image",
        postUniq: "Unique posters",
        postPop: "Most active poster",
        filters: "Filters",

        errorUserNotFound: "Error: User not found.",
        errorUserWrongCredentials: "Error: Invalid username or password.",
        errorUserNotAuthorized: "Error: You don'have the necessary permissions to acces this resource.",
        errorUserNotAdmin: "Error: You are not the administrator.",
        errorUserPreventSeppuku: "Error: You can't delete yourself from the user list!",
        errorDeletionError: "Error: Something is preventing user elimination.", // ask balu?
        errorNotFound: "Error: Resource not found.",
        errorMissingFields: "Error: One ore more requested fields haven't been compiled.",
        errorAlreadyExists: "Error: Resource already exists.",
        errorEnumInvalid: "Error: Unknown data type.",
        errorUnknownError: "Unknown error.",
        errorNoJson: "Error: Sent a request without body.",
        errorRepositoryNotFound: "Error: Repository not found.",
        errorRepositoryNotOwner: "Error: You aren't the owner of this repository!",
        errorRepositoryDepencencyFailure: "Error: Something is preventing repository elimination",
        errorConditionNotFound: "Error: Specified an invalid condition.",
        errorAlertNotFound: "Error: Alert not found.",
        errorAlertNoName: "Error: Didn't specify alert name.",
        errorAlertNoLimit: "Error: Didn't specify alert threshold.",
        errorAlertNoWindow: "Error: Didn't specify alert window size.",
        errorAlertNoEvaluation: "Error: Didn't specify evaluation mode.",
        errorAlertDeletionFailure: "Error: Something is preventing alert elimination.",
        errorViewNotAllowed: "Error: You are not allowed to make the request.", //Non so come scriverlo meglio
        errorServerNotConfigured: "Error: Server not configured.",
        errorDecodeError: "Error: Could not deserialize data recieved from backend.",
        errorSerializationError: "Error: Could not serialize the data to be sent to backend.",
        errorPageNotFound: "Error: Page not found.",
    },
    // 🇫🇮
    fi: {
        appName: "N.E.S.T.",
        appFullName: "Poimimme Twiittien Tilastot",
        welcomeToNest: "Tervetuloa N.E.S.T.:hen!", //Certo che il Finlandese è proprio strano

        resolutionTooSmall: "Tämän sovelluksen asianmukainen katselu edellyttää näyttöä, jonka resoluutio on vähintään 1366x768.",
        ignore: "Näytä joka tapauksessa",

        server: "Valitse palvelin",
        baseURL: "Perus-URL",
        notLoggedIn: "Ei kirjautunut sisään",
        login: "Kirjaudu sisään",
        email: "Sähköposti",
        passwd: "Salasana",

        dashboardTitle: "Luo uusi arkisto",
        dashboard: "Kojelauta",
        searchBy: "Haku ",
        byZone: "vyöhykkeen mukaan",
        byHashtag: "hashtagin mukaan",
        byUser: "käyttäjän mukaan",
        byRetweet: "uudelleentwiittauksen mukaan",
        isNotRetweetExplaination: "Piilota uudelleentwiittaukset.",
        byHasImage: "kuva",
        hasImageExplaination: "Näytä vain twiitit, joissa on kuva.",
        byTimePeriod: "aikajakson mukaan",
        byContents: "sisältö",
        byHasPlace: "kiinnostuksen kohde",
        hasPlaceExplaination: "Näytä vain twiitit, joihin liittyy kiinnostava kohde.",
        timeBefore: "Ennen",
        timeAfter: "Jälkeen",
        conditions: "Ehdot",
        createRepo: "Luo arkisto",
        repoName: "Arkiston nimi",
        request: "Pyydä",
        filterOR: "Vähintään yksi ehto",
        filterAND: "Kaikki ehdot",
        rollback: "Peruuta muutokset",
        save: "Tallenna muutokset",
        wordcloud: "Sanapilvi",

        repositories: "Arkistot",
        repoMenu: "Arkistot-valikko",
        repoEdit: "Muokkaa arkistoa",
        menuActive: "Aktiiviset arkistosi",
        menuArchived: "Arkistoidut arkistosi",
        emptyMenu: "Täällä ei ole mitään.",
        delete: "Poista",
        share: "Osake",
        unshare: "Peruuta jakaminen", // Potrebbe voler dire tutt'altra cosa, ma ho già combattuto abbastanza per una singola frase
        archive: "Arkistoi",
        edit: "Muokkaa",
        created: "Luotu",
        archived: "Arkisto",

        repoShare: "Osake",
        availableUsers: "Käytettävissä olevat käyttäjät",
        sharingWith: "Jakaminen seuraavien kanssa",

        alerts: "Hälytykset",
        alertTitle: "Tähän arkistoon liittyvät hälytyksesi",
        alertCreate: "Luo uusi hälytys",
        alertName: "Hälytyksen nimi",
        createAlert: "Luo hälytys",
        alertLimit: "Kynnysarvo",
        alertWindow: "Ikkunan koko (tunteina)",

        notImplemented: "🚧 Ei toteutettu.",

        settings: "Asetukset",
        loggedInTitle: "Kirjautunut sisään",
        loggedInOn: "Olet tällä hetkellä kirjautuneena sisään",
        loggedInAs: "nimellä",
        logout: "Kirjaudu ulos",
        switchTheme: "Vaihda teema",
        darkMode: "Tumma",
        lightMode: "Selkeä",
        changeLang: "Vaihda kieltä",
        alertSettings: "Hälytysasetukset",
        changeEmail: "Vaihda sähköpostiosoitteesi",
        changePasswd: "Vaihda salasanasi",

        users: "Käyttäjät",
        manageUsers: "Käyttäjien hallinta",
        userList: "Käyttäjäluettelo",
        userCreate: "Luo uusi käyttäjä",
        userName: "Käyttäjätunnus",
        create: "Luo",
        type: "Tyyppi",
        admin: "Ylläpitäjä",
        user: "Käyttäjä",

        repoDeleted: "Tämä arkisto on poistettu.",
        tweets: "Twiitit",
        hourlyGraph: "Tuntikohtainen kaavio",
        visualMap: "Kartta",
        stats: "Tilastot",
        totTweets: "Twiitit yhteensä",
        dispTweets: "Näytetyt twiitit",
        dispTweetsPerc: "% näytetyistä twiiteistä",
        locTweets: "Twiitit, joissa on sijainti",
        locTweetsPerc: "% twiiteistä, joissa on sijainti",
        contTweets: "Sisältöä sisältävät twiitit",
        contTweetsPerc: "% sisältöä sisältävistä twiiteistä",
        wordCount: "Sanojen määrä",
        wordPop: "Suosituin sana",
        imgTweets: "Twiitit, joissa on kuva",
        imgTweetsPerc: "% twiiteistä, joissa on kuva",
        postUniq: "Ainutkertaiset käyttäjät",
        postPop: "Aktiivisimmat käyttäjät",
        filters: "Suodattimet",

        errorUserNotFound: "Virhe: Käyttäjää ei löydy.",
        errorUserWrongCredentials: "Virhe: Virheellinen käyttäjätunnus tai salasana.",
        errorUserNotAuthorized: "Virhe: Sinulla ei ole tarvittavia oikeuksia käyttää tätä resurssia.",
        errorUserNotAdmin: "Virhe: Et ole ylläpitäjä.",
        errorUserPreventSeppuku: "Virhe: Et voi poistaa itseäsi käyttäjäluettelosta!",
        errorDeletionError: "Virhe: Jokin estää käyttäjän poistamisen.", // ask balu?
        errorNotFound: "Virhe: Resurssia ei löydy.",
        errorMissingFields: "Virhe: Yhtä tai useampaa pyydettyä kenttää ei ole koottu.",
        errorAlreadyExists: "Virhe: Resurssi on jo olemassa.",
        errorEnumInvalid: "Virhe: Tuntematon tietotyyppi.",
        errorUnknownError: "Tuntematon virhe.",
        errorNoJson: "Virhe: Lähetetty pyyntö ilman runkoa.",
        errorRepositoryNotFound: "Virhe: Arkistoa ei löydy.",
        errorRepositoryNotOwner: "Virhe: Et ole arkiston omistaja!",
        errorRepositoryDepencencyFailure: "Virhe: Jokin estää arkiston poistamisen.",
        errorConditionNotFound: "Virhe: Määritettiin virheellinen ehto.",
        errorAlertNotFound: "Virhe: Hälytystä ei löydy.",
        errorAlertNoName: "Virhe: Ei määritetty hälytyksen nimeä.",
        errorAlertNoLimit: "Virhe: Ei määritetty hälytyskynnystä.",
        errorAlertNoWindow: "Virhe: Ei määritetty hälytysikkunan kokoa.",
        errorAlertNoEvaluation: "Virhe: Ei määritetty arviointitilaa.",
        errorAlertDeletionFailure: "Virhe: Jokin estää hälytyksen poistamisen.",
        errorViewNotAllowed: "Virhe: Et saa esittää pyyntöä.",
        errorServerNotConfigured: "Virhe: Palvelinta ei ole määritetty.",
        errorDecodeError: "Virhe: Backendistä saatuja tietoja ei voitu deserialisoida.",
        errorSerializationError: "Virhe: Backendiin lähetettävää dataa ei voitu serialisoida.",
        errorPageNotFound: "Virhe: sivua ei löydy.",
    },
}